#!/bin/bash

yum install -y which wget tar gcc gcc-c++ unzip
yum install -y gcc bzip2-devel libffi-devel perl
yum install -y zlib zlib-devel git bzip2

to_download=(
"https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz" \
"https://www.openssl.org/source/old/1.1.1/openssl-1.1.1g.tar.gz" \
"https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz"
)

for t in ${to_download[@]}
do
    while ! wget --tries=10 --timeout=5 --no-check-certificate $t
    do
        echo "-------RETRY"
    done
done

# build utils
tar -xzf cmake-3.23.2-linux-x86_64.tar.gz
export PATH=$PWD/cmake-3.23.2-linux-x86_64/bin:$PATH

# build openssl
tar -xzf openssl-1.1.1g.tar.gz
cd openssl-1.1.1g
ssl_dir=$PWD/openssl_installation
./config --prefix=$ssl_dir --openssldir=$ssl_dir no-ssl2
make -j 16
make install
export LD_LIBRARY_PATH=$ssl_dir/lib
export PATH=$ssl_dir/bin:$PATH
cd ../


# build python 3.7.0
tar -xzf Python-3.7.0.tgz
cd Python-3.7.0
python_dir=$PWD/py_installation
./configure --enable-optimizations --prefix=$python_dir --with-openssl=$ssl_dir
make -j8 altinstall
export PATH=$python_dir/bin:$PATH
cd ../

# env settings
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH" > env
echo "export PATH=$PATH" >> env

