#!/bin/bash

# some preparation
rm -rf install_artefacts_nvim
mkdir install_artefacts_nvim
cd install_artefacts_nvim

#----------------------------------------------------

# get glibc-2.14
wget --tries=10 --timeout=5 http://ftp.gnu.org/gnu/glibc/glibc-2.14.tar.gz

# get ripgrep
wget --tries=10 --timeout=5 https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz

# get nvim
wget --tries=10 --timeout=5 https://github.com/neovim/neovim/releases/latest/download/nvim.appimage

# get config for nvim
wget --tries=10 --timeout=5 https://github.com/andr-savel/NvimIDE/archive/refs/heads/main.zip

# get neovim python module
wget --tries=10 --timeout=5 https://files.pythonhosted.org/packages/0c/10/754e21b5bea89d0e73f99d60c83754df7cc64db74f47d98ab187669ce341/greenlet-1.1.2.tar.gz

    wget --tries=10 --timeout=5 https://files.pythonhosted.org/packages/ad/58/015e95071f70522c71d54bf5deddffbca07967bfebc78e7ae0e545723d84/Cython-0.29.30-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
    wget --tries=10 --timeout=5 https://files.pythonhosted.org/packages/e9/86/b2ede1d87122a6d4da86d84cc35d0e48b4aa2476e4281d06101c772c1961/setuptools-62.6.0-py3-none-any.whl
wget --tries=10 --timeout=5 https://files.pythonhosted.org/packages/22/44/0829b19ac243211d1d2bd759999aa92196c546518b0be91de9cacc98122a/msgpack-1.0.4.tar.gz

wget --tries=10 --timeout=5 https://files.pythonhosted.org/packages/7a/01/2d0898ba6cefbe2736283ee3155cba1c602de641ca5667ac55a0e4857276/pynvim-0.4.3.tar.gz
wget --tries=10 --timeout=5 https://files.pythonhosted.org/packages/78/ec/ac9905ccab8774b64c37cdff9e08db320c349eda0ae3161aebcac83e5590/neovim-0.3.1.tar.gz

#---------------------------------------------------

cd ../

# install fuse libraries (it is used to run nvim appimage)
yum install -y fuse-libs

# install xclip
yum install -y xclip

#---------------------------------------------------
cd ../
