#!/bin/bash

# some preparation
rm -rf install_result
mkdir install_result
cd install_artefacts_nvim

#----------------------- build and install system parts

# build glibc-2.14
tar -xzf glibc-2.14.tar.gz
cd glibc-2.14
mkdir build
cd build/
glibc_dir=$PWD/glibc_installation
../configure --prefix=$glibc_dir
make -j8
make install
export LD_LIBRARY_PATH=$glibc_dir/lib:$LD_LIBRARY_PATH
cd ../../

# install ripgrep
tar -xzf ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz
cp ripgrep-13.0.0-x86_64-unknown-linux-musl/rg ../install_result

# install nvim
chmod +x nvim.appimage
cp nvim.appimage ../install_result

# get config for nvim
unzip main.zip
cp -dr NvimIDE-main ../install_result

# install neovim python module with dependencies
python3.7 -m pip install --user neovim --find-links=. --no-index

# install compdb python module
python3.7 -m pip install --user ./compdb-0.2.0.tar.gz

# install pyright python language server
python3.7 -m pip install --user pyright --find-links=. --no-index

#------------------------- build and install config and plugins

mkdir -p ~/.config/nvim
ln -s $PWD/../install_result/NvimIDE-main/config/* ~/.config/nvim

mkdir -p ~/.local/share/nvim
cd ../
tar -xzf local_share_nvim.tar.gz
cd -
cp -dr ../local_share_nvim/* ~/.local/share/nvim

for t in `ls tree-sitter-*`
do
    prefix=`echo $t | awk -F "." '{print $1}'`
    mkdir $prefix
    lang=`echo $prefix | awk -F "-" '{print $3}'`

    tar -xzf $t -C $prefix
    cd `ls -d $prefix/*`

    cc -o parser.so -I./src  src/*c -shared -Os -lstdc++ -fPIC -DUINT8_MAX=255
    mv parser.so ~/.local/share/nvim/plugged/nvim-treesitter/parser/$lang.so

    cd ../../
done
    

# env settings
echo "---------------------------- env settings"
echo "    LIB"
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

